var vacCountryToIso3 = {
	Austria: "AUT",
BEL: "Belgium",
BGR: "Bulgaria",
CHL: "Chile",
CYP: "Cyprus",
HRV: "Croatia",

CZE: "Czechia",
DNK: "Denmark",
ECU: "Ecuador",
EST: "Estonia",

FIN: "Finland",

FRA: "France",
DEU: "Germany",
HKG: "Hong Kong",
HUN: "Hungary",
ISL: "Iceland",
ITA: "Italy",
JPN: "Japan",
LVA: "Latvia",
LIE: "Liechtenstein",
LTU: "Lithuania",
LUX: "Luxembourg",
MLT: "Malta",
NLD: "Netherlands",
NOR: "Norway",
POL: "Poland",
PRT: "Portugal",
ROU: "Romania",
SVK: "Slovakia",
KOR: "South Korea",
ESP: "Spain",
SWE: "Sweden",
CHE: "Switzerland",
USA: "United States",
URY: "Uruguay"};
